import React from 'react';

export const DUMMY_LIST_KOTA = [
  { provinsi: "Aceh", kota: "a" },
  { provinsi: "Aceh", kota: "b" },
  { provinsi: "Banten", kota: "c" },
  { provinsi: "Aceh", kota: "d" },
  { provinsi: "Banten", kota: "e" },
];

export const DUMMY_LIST_PROVINSI = [
    {
      provinsi: "Aceh",
      rumahSakit: true,
      infoOksigen: true,
      lokasiVaksinasi: true,
      kasusAktif: "100",
    },
    {
      provinsi: "Bali",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: true,
      kasusAktif: "100",
    },
    {
      provinsi: "Bangka Belitung",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Banten",
      rumahSakit: true,
      infoOksigen: true,
      lokasiVaksinasi: true,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
    {
      provinsi: "Bengkulu",
      rumahSakit: true,
      infoOksigen: false,
      lokasiVaksinasi: false,
      kasusAktif: "100",
    },
  ];
